[sources.mongodb]
restore_from_destination=false

[destination.bigquery]
location = "EU"

[sources.mongodb_pipeline.data_writer]
buffer_max_items=1000
file_max_items=1000
file_max_bytes=10000

[extract]
worker=5
max_parallel_items=1000
